# This is a basic workflow to help you get started with Actions

name: "Create pull request"

# Controls when the action will run. Triggers the workflow on push 
# events but only for branches with the following branch spec: "beta/pipelinebuild/*"
on:
  push:
    branches:
      - "beta/pipelinebuild/*"  # Support wildcard matching

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create-pull-request"
  create-pull-request:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Create a pull request
    # https://developer.github.com/v3/pulls/#create-a-pull-request
    - name: Create PR using the GitHub REST API
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pulls
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Generated models and request builders using Typewriter",
          "head": "${{ github.ref }}",
          "base": "master",
          "body": "This pull request was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_. \n\n **Important** Check for unexpected deletions or changes in this PR.",
          "draft": false
          }'
    
    # Add pull request reviewers
    # https://developer.github.com/v3/pulls/review_requests/#create-a-review-request
    #- name: Add PR reviewers using the GitHub REST API

    # Assign the pull request. Because PRs are issues.
    # https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue
